[package]
name = "adventofcode22"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "*"
log = "0.4"
simple_logger = "4.0.0"
test-log = "0.2.11"